language: clojure

jvm:
  - openjdk7
  - oraclejdk7
  - openjdk6

lein: lein2

script: lein2 all test

# May need other tools later
before_install:
  - sudo apt-get update
  - sudo apt-get install verilog

branches:
  only:
    - master
